name: Live Elements Web Build Matrix

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        include:
        - os: ubuntu-18.04
          NAME: ubuntu
          TARGET: x86_64-linux
          COMPILER: g++
          LINKER: g++

    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        env:
          ARCHIVE_NAME: ${{ steps.get_archive_name.outputs.ARCHIVE_FILENAME }}
        
      - name: Install deps
        run: npm install

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'ubuntu-18.04')
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          cd ../live-elements-core
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access=public
          cd ../live-elements-loader
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access=public
          cd ../live-elements-web
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access=public
          cd ../live-elements-web-cli
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access=public
          cd ../live-web
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access=public
          cd ../live-testspec
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access=public